import { launchBrowser, openPage } from './tools/critic/browser.mjs';
import { writeFileSync, mkdirSync } from 'node:fs';
mkdirSync('shots', { recursive: true });
const planet = process.argv[2] || 'aurvangr';
const view = process.argv[3] || '0';
const tier = process.argv[4] || 'medium';
const b = await launchBrowser();
const { page, errors } = await openPage(b, { width: 1280, height: 720 });
await page.goto(`http://127.0.0.1:5199/world-test.html?planet=${planet}&view=${view}&tier=${tier}`, { waitUntil:'domcontentloaded', timeout:60000 });
const ok = await page.waitForFunction(() => window.WORLD?.done, { timeout: 480000 }).then(()=>true).catch(()=>false);
console.log(ok?'OK':'TIMEOUT', JSON.stringify(await page.evaluate(()=>window.WORLD??null)));
console.log('stages:', JSON.stringify(await page.evaluate(()=>window.WORLD_STAGES??[]), null, 0));
await page.waitForTimeout(500);
writeFileSync(`shots/world-${planet}-v${view}.png`, await page.screenshot());
errors.slice(0,6).forEach(e=>console.log('ERR', e.split('\n').slice(0,3).join(' | ')));
await b.close();
